# Generated by Django 2.0.2 on 2018-03-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('video_title', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('video_title', models.CharField(max_length=500)),
                ('video_url', models.CharField(max_length=1000)),
                ('main_category', models.CharField(max_length=250)),
                ('sub_category', models.CharField(max_length=250)),
                ('normalized_words', models.CharField(max_length=1000000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Category')),
            ],
        ),
    ]
